package com.example.active_portfolio_mobile.composables.adventure

import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AddPhotoAlternate
import androidx.compose.material3.Button
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp

/**
 * An image picker which allows an image to be uploaded from the device's storage.
 * This composable was generated by MS Copilot.
 * @param onImageSelected a function determining what to do with the selected image,
 * e.g. pass it into a viewModel function which will save it for later use.
 */
@Composable
fun ImagePicker(onImageSelected: (Bitmap) -> Unit) {
    val context = LocalContext.current

    val launcher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.GetContent()
    ) { uri: Uri? ->
        uri?.let {
            val inputStream = context.contentResolver.openInputStream(uri)
            val bitmap = BitmapFactory.decodeStream(inputStream)
            onImageSelected(bitmap)
        }
    }

    Button(onClick = { launcher.launch("image/*") },
        modifier = Modifier.padding(vertical = 20.dp)
        ) {
        Icon(imageVector = Icons.Filled.AddPhotoAlternate,
            contentDescription = "Add an image from the device's gallery",
            modifier = Modifier.size(30.dp)
        )
    }
}

