name: release build

on:
  push:
    branches: ["main", "Testing-CICD-workflows"]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Give permissions for gradlew execution
        run: chmod +x ./gradlew

      - name: Run Gradle build
        run: ./gradlew build